//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ajax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public int OwnerID { get; set; }
        public string Name { get; set; }
        public string Pswd { get; set; }
        public string UserName { get; set; }
        public string Lock { get; set; }
    }
}
