//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ajax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerAddOn
    {
        public int OwnerId { get; set; }
        public string PhoneNumber { get; set; }
        public string Locality { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Email { get; set; }
    }
}
