//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ajax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyDetail
    {
        public int PropertyID { get; set; }
        public int OwnerID { get; set; }
        public string PropertyType { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string nState { get; set; }
        public string PinCode { get; set; }
        public Nullable<decimal> Rent { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Images { get; set; }
    }
}
