//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ajax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recfrombrok
    {
        public int RecomendID { get; set; }
        public string location { get; set; }
        public Nullable<int> NoOfRooms { get; set; }
        public Nullable<int> Maxamount { get; set; }
        public Nullable<int> Minamount { get; set; }
        public string req1 { get; set; }
        public string req2 { get; set; }
        public string req3 { get; set; }
        public Nullable<int> propidone { get; set; }
        public Nullable<int> propidtwo { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<int> BrokId { get; set; }
    }
}
